services:
  app:
    build: .
    command: .docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    #   - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
